---
- hosts: all
  become: true
  vars:
    INSTANCE_IP: 10.10.10.10

  pre_tasks:
    - name: Verify Ansible meets version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.8', '>=')"
        msg: >
          "You must update Ansible to at least 2.8 to use this script."

  roles:
    - common
    - shares
    - users
    - post-boot
    - cleanup
